export const initialDrivers = [
  { id: 'DRV-101', name: 'Asha Rao', status: 'Available', specialization: 'Cold Chain' },
  { id: 'DRV-102', name: 'Milan Shah', status: 'Unavailable', specialization: 'Heavy Cargo' },
  { id: 'DRV-103', name: 'Nadia Khan', status: 'Available', specialization: 'Express' },
  { id: 'DRV-104', name: 'Rohit Verma', status: 'Available', specialization: 'Regional' },
];

export const initialVehicles = [
  { id: 'VEH-201', name: 'VR-12', status: 'Available', capacityKg: 650 },
  { id: 'VEH-202', name: 'TR-04', status: 'On Trip', capacityKg: 1800 },
  { id: 'VEH-203', name: 'EV-09', status: 'Available', capacityKg: 420 },
  { id: 'VEH-204', name: 'TR-07', status: 'Available', capacityKg: 2200 },
];

export const initialTrips = [
  {
    id: 'TRIP-102',
    source: 'Central Depot',
    destination: 'North Hub',
    cargoWeight: 540,
    distance: 82,
    duration: '2h 15m',
    vehicleId: 'VEH-201',
    vehicleName: 'VR-12',
    driverId: 'DRV-101',
    driverName: 'Asha Rao',
    dispatchDate: '2026-07-12',
    expectedArrival: '2026-07-12T15:15',
    notes: 'Priority cold chain delivery.',
    status: 'Dispatched',
  },
  {
    id: 'TRIP-103',
    source: 'Harbor Yard',
    destination: 'West Terminal',
    cargoWeight: 900,
    distance: 124,
    duration: '4h 10m',
    vehicleId: 'VEH-204',
    vehicleName: 'TR-07',
    driverId: 'DRV-104',
    driverName: 'Rohit Verma',
    dispatchDate: '2026-07-13',
    expectedArrival: '2026-07-13T17:20',
    notes: 'High-volume freight to support the evening shift.',
    status: 'Draft',
  },
  {
    id: 'TRIP-104',
    source: 'Airport Gate',
    destination: 'City Center',
    cargoWeight: 310,
    distance: 36,
    duration: '1h 10m',
    vehicleId: 'VEH-203',
    vehicleName: 'EV-09',
    driverId: 'DRV-103',
    driverName: 'Nadia Khan',
    dispatchDate: '2026-07-12',
    expectedArrival: '2026-07-12T11:35',
    notes: 'Express handoff for retail stock.',
    status: 'Completed',
  },
];
