export const permissions = {
  FLEET_MANAGER: {
    dashboard: 'view',
    fleet: 'edit',
    drivers: 'edit',
    trips: 'edit',
    maintenance: 'edit',
    fuelExpenses: 'view',
    analytics: 'view',
    settings: 'view',
  },
  DISPATCHER: {
    dashboard: 'view',
    fleet: 'view',
    drivers: 'none',
    trips: 'edit',
    maintenance: 'none',
    fuelExpenses: 'none',
    analytics: 'none',
    settings: 'view',
  },
  SAFETY_OFFICER: {
    dashboard: 'view',
    fleet: 'none',
    drivers: 'none',
    trips: 'view',
    maintenance: 'none',
    fuelExpenses: 'none',
    analytics: 'none',
    settings: 'view',
  },
  FINANCIAL_ANALYST: {
    dashboard: 'view',
    fleet: 'none',
    drivers: 'none',
    trips: 'none',
    maintenance: 'none',
    fuelExpenses: 'edit',
    analytics: 'view',
    settings: 'view',
  },
};
